# Generated by Django 4.1.5 on 2023-03-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_cartitems_book_remove_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('image_url_m', models.URLField()),
                ('num_ratings', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
