# Generated by Django 4.1.5 on 2023-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookadd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAdd',
        ),
    ]
