# Generated by Django 4.1.5 on 2023-03-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_bookadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
